//Dados mockados para testar a validação dos campos do laboratório

export const MockLabs = [
  {
    enviroment: "1abcd",
    name: "Lab 01",
    opening_time: "13:00",
    closing_time: "16:00",
    qty_chairs: 20,
    qty_computers: 15,
    television: true,
    fan: false,
    air_conditioner: true,
    is_activated: true,
  },
  {
    enviroment: "2abcd",
    name: "Lab 02",
    opening_time: "15:30",
    closing_time: "18:20",
    qty_chairs: 25,
    qty_computers: 20,
    television: false,
    fan: true,
    air_conditioner: false,
    is_activated: true,
  },
  {
    enviroment: "3abcd",
    name: "Lab 03",
    opening_time: "11:00",
    closing_time: "12:00",
    qty_chairs: 18,
    qty_computers: 10,
    television: true,
    fan: true,
    air_conditioner: false,
    is_activated: false,
  },
  {
    enviroment: "4abcd",
    name: "Lab 04",
    opening_time: "09:00",
    closing_time: "14:30",
    qty_chairs: 30,
    qty_computers: 25,
    television: false,
    fan: false,
    air_conditioner: true,
    is_activated: true,
  },
  {
    enviroment: "5abcd",
    name: "Lab 05",
    opening_time: "10:45",
    closing_time: "19:00",
    qty_chairs: 22,
    qty_computers: 18,
    television: true,
    fan: false,
    air_conditioner: true,
    is_activated: true,
  },
  {
    enviroment: "6abcd",
    name: "Lab 06",
    opening_time: "07:00",
    closing_time: "12:00",
    qty_chairs: 15,
    qty_computers: 12,
    television: false,
    fan: true,
    air_conditioner: false,
    is_activated: false,
  },
  // {
  //   enviroment: "7abcd",
  //   name: "Lab 07",
  //   opening_time: "08:30",
  //   closing_time: "12:30",
  //   qty_chairs: 20,
  //   qty_computers: 15,
  //   television: false,
  //   fan: true,
  //   air_conditioner: false,
  //   is_activated: true,
  // },
  // {
  //   enviroment: "8abcd",
  //   name: "Lab 08",
  //   opening_time: "13:15",
  //   closing_time: "17:45",
  //   qty_chairs: 28,
  //   qty_computers: 22,
  //   television: true,
  //   fan: false,
  //   air_conditioner: true,
  //   is_activated: true,
  // },
  // {
  //   enviroment: "9abcd",
  //   name: "Lab 09",
  //   opening_time: "10:00",
  //   closing_time: "14:00",
  //   qty_chairs: 18,
  //   qty_computers: 16,
  //   television: true,
  //   fan: true,
  //   air_conditioner: true,
  //   is_activated: false,
  // },
  // {
  //   enviroment: "10bcd",
  //   name: "Lab 10",
  //   opening_time: "07:45",
  //   closing_time: "11:30",
  //   qty_chairs: 24,
  //   qty_computers: 20,
  //   television: false,
  //   fan: false,
  //   air_conditioner: false,
  //   is_activated: true,
  // },
];
